import type { Planet } from "./types";
import { calculateHabitabilityScore, calculateDataConfidence } from "./habitability";
import { slugifyPlanetName } from "./utils";

type RawPlanet = Omit<Planet, "id" | "habitabilityScore" | "dataConfidence">;

const rawFallback: RawPlanet[] = [
  {
    name: "Proxima Centauri b",
    hostStar: "Proxima Centauri",
    stellarTeff: 3050,
    radiusEarth: 1.08,
    massEarth: 1.27,
    orbitalPeriodDays: 11.2,
    equilibriumTempK: 234,
    discoveryYear: 2016,
    discoveryMethod: "Radial Velocity",
    distanceParsecs: 1.295,
    distanceLightYears: 4.22,
  },
  {
    name: "TRAPPIST-1 e",
    hostStar: "TRAPPIST-1",
    stellarTeff: 2566,
    radiusEarth: 0.92,
    massEarth: 0.69,
    orbitalPeriodDays: 6.1,
    equilibriumTempK: 251,
    discoveryYear: 2017,
    discoveryMethod: "Transit",
    distanceParsecs: 12.1,
    distanceLightYears: 39.5,
  },
  {
    name: "TRAPPIST-1 f",
    hostStar: "TRAPPIST-1",
    stellarTeff: 2566,
    radiusEarth: 1.04,
    massEarth: 1.04,
    orbitalPeriodDays: 9.2,
    equilibriumTempK: 219,
    discoveryYear: 2017,
    discoveryMethod: "Transit",
    distanceParsecs: 12.1,
    distanceLightYears: 39.5,
  },
  {
    name: "Kepler-452 b",
    hostStar: "Kepler-452",
    stellarTeff: 5757,
    radiusEarth: 1.63,
    massEarth: 5.0,
    orbitalPeriodDays: 384.8,
    equilibriumTempK: 265,
    discoveryYear: 2015,
    discoveryMethod: "Transit",
    distanceParsecs: 430.0,
    distanceLightYears: 1402.0,
  },
  {
    name: "Kepler-186 f",
    hostStar: "Kepler-186",
    stellarTeff: 3788,
    radiusEarth: 1.17,
    massEarth: null,
    orbitalPeriodDays: 129.9,
    equilibriumTempK: 188,
    discoveryYear: 2014,
    discoveryMethod: "Transit",
    distanceParsecs: 178.5,
    distanceLightYears: 582.0,
  },
  {
    name: "LHS 1140 b",
    hostStar: "LHS 1140",
    stellarTeff: 3216,
    radiusEarth: 1.73,
    massEarth: 6.98,
    orbitalPeriodDays: 24.7,
    equilibriumTempK: 235,
    discoveryYear: 2017,
    discoveryMethod: "Transit",
    distanceParsecs: 14.99,
    distanceLightYears: 48.9,
  },
  {
    name: "K2-18 b",
    hostStar: "K2-18",
    stellarTeff: 3503,
    radiusEarth: 2.71,
    massEarth: 8.63,
    orbitalPeriodDays: 32.9,
    equilibriumTempK: 265,
    discoveryYear: 2015,
    discoveryMethod: "Transit",
    distanceParsecs: 38.0,
    distanceLightYears: 124.0,
  },
  {
    name: "TOI-700 d",
    hostStar: "TOI-700",
    stellarTeff: 3459,
    radiusEarth: 1.19,
    massEarth: null,
    orbitalPeriodDays: 37.4,
    equilibriumTempK: 246,
    discoveryYear: 2020,
    discoveryMethod: "Transit",
    distanceParsecs: 31.1,
    distanceLightYears: 101.4,
  },
  {
    name: "GJ 667 Cc",
    hostStar: "GJ 667 C",
    stellarTeff: 3350,
    radiusEarth: null,
    massEarth: 3.8,
    orbitalPeriodDays: 28.1,
    equilibriumTempK: 277,
    discoveryYear: 2011,
    discoveryMethod: "Radial Velocity",
    distanceParsecs: 6.84,
    distanceLightYears: 22.3,
  },
  {
    name: "Ross 128 b",
    hostStar: "Ross 128",
    stellarTeff: 3192,
    radiusEarth: null,
    massEarth: 1.35,
    orbitalPeriodDays: 9.9,
    equilibriumTempK: 294,
    discoveryYear: 2017,
    discoveryMethod: "Radial Velocity",
    distanceParsecs: 3.37,
    distanceLightYears: 11.0,
  },
  {
    name: "55 Cancri e",
    hostStar: "55 Cancri",
    stellarTeff: 5196,
    radiusEarth: 1.88,
    massEarth: 7.99,
    orbitalPeriodDays: 0.74,
    equilibriumTempK: 1958,
    discoveryYear: 2004,
    discoveryMethod: "Radial Velocity",
    distanceParsecs: 12.34,
    distanceLightYears: 40.3,
  },
  {
    name: "HD 209458 b",
    hostStar: "HD 209458",
    stellarTeff: 6117,
    radiusEarth: 14.0,
    massEarth: 220.0,
    orbitalPeriodDays: 3.52,
    equilibriumTempK: 1450,
    discoveryYear: 2000,
    discoveryMethod: "Transit",
    distanceParsecs: 48.0,
    distanceLightYears: 156.6,
  },
  {
    name: "WASP-12 b",
    hostStar: "WASP-12",
    stellarTeff: 6250,
    radiusEarth: 20.2,
    massEarth: 459.0,
    orbitalPeriodDays: 1.09,
    equilibriumTempK: 2580,
    discoveryYear: 2008,
    discoveryMethod: "Transit",
    distanceParsecs: 427.0,
    distanceLightYears: 1393.0,
  },
  {
    name: "Kepler-22 b",
    hostStar: "Kepler-22",
    stellarTeff: 5518,
    radiusEarth: 2.38,
    massEarth: null,
    orbitalPeriodDays: 289.9,
    equilibriumTempK: 262,
    discoveryYear: 2011,
    discoveryMethod: "Transit",
    distanceParsecs: 190.0,
    distanceLightYears: 620.0,
  },
  {
    name: "Kepler-10 b",
    hostStar: "Kepler-10",
    stellarTeff: 5708,
    radiusEarth: 1.47,
    massEarth: 3.72,
    orbitalPeriodDays: 0.84,
    equilibriumTempK: 2169,
    discoveryYear: 2011,
    discoveryMethod: "Transit",
    distanceParsecs: 173.0,
    distanceLightYears: 564.0,
  },
  {
    name: "GJ 1214 b",
    hostStar: "GJ 1214",
    stellarTeff: 3026,
    radiusEarth: 2.68,
    massEarth: 6.26,
    orbitalPeriodDays: 1.58,
    equilibriumTempK: 393,
    discoveryYear: 2009,
    discoveryMethod: "Transit",
    distanceParsecs: 14.55,
    distanceLightYears: 47.5,
  },
  {
    name: "Tau Ceti e",
    hostStar: "Tau Ceti",
    stellarTeff: 5344,
    radiusEarth: null,
    massEarth: 3.93,
    orbitalPeriodDays: 168.1,
    equilibriumTempK: 342,
    discoveryYear: 2012,
    discoveryMethod: "Radial Velocity",
    distanceParsecs: 3.65,
    distanceLightYears: 11.9,
  },
  {
    name: "Teegarden's Star b",
    hostStar: "Teegarden's Star",
    stellarTeff: 2904,
    radiusEarth: null,
    massEarth: 1.05,
    orbitalPeriodDays: 4.91,
    equilibriumTempK: 264,
    discoveryYear: 2019,
    discoveryMethod: "Radial Velocity",
    distanceParsecs: 3.83,
    distanceLightYears: 12.5,
  },
  {
    name: "Kepler-1649 c",
    hostStar: "Kepler-1649",
    stellarTeff: 3240,
    radiusEarth: 1.06,
    massEarth: null,
    orbitalPeriodDays: 19.5,
    equilibriumTempK: 234,
    discoveryYear: 2020,
    discoveryMethod: "Transit",
    distanceParsecs: 90.0,
    distanceLightYears: 293.7,
  },
  {
    name: "Wolf 1061 c",
    hostStar: "Wolf 1061",
    stellarTeff: 3342,
    radiusEarth: null,
    massEarth: 4.25,
    orbitalPeriodDays: 17.9,
    equilibriumTempK: 271,
    discoveryYear: 2015,
    discoveryMethod: "Radial Velocity",
    distanceParsecs: 4.31,
    distanceLightYears: 14.1,
  },
];

export const fallbackPlanets: Planet[] = rawFallback.map((raw, index) => {
  const partial = { ...raw };
  const habitabilityScore = calculateHabitabilityScore(partial);
  const dataConfidence = calculateDataConfidence(partial);
  return {
    ...partial,
    id: slugifyPlanetName(raw.name, index),
    habitabilityScore,
    dataConfidence,
  };
});
