import { NextRequest, NextResponse } from "next/server";
import https from "https";
import { calculateHabitabilityScore, calculateDataConfidence } from "@/lib/habitability";
import { slugifyPlanetName, toNumberOrNull, deduplicateIds } from "@/lib/utils";
import type { Planet, ChunkResponse } from "@/lib/types";

/* ── Server-side planet cache ────────────────────────────────────────────────
   NASA is fetched once per server process lifetime (or after CACHE_TTL).
   All client chunk requests are served from this in-memory store — instant.  */

const CACHE_TTL = 60 * 60 * 1000; // 1 hour
let serverCache: { planets: Planet[]; at: number } | null = null;
let fetchPromise: Promise<Planet[]> | null = null;

const NASA_TAP = "https://exoplanetarchive.ipac.caltech.edu/TAP/sync";
const SQL = "SELECT pl_name,hostname,disc_year,discoverymethod,pl_rade,pl_bmasse,pl_orbper,pl_eqt,sy_dist,st_teff FROM pscomppars WHERE pl_name IS NOT NULL ORDER BY disc_year DESC";

// Re-export so old imports don't break
export type { ChunkResponse };

interface NasaRow {
  pl_name: string; hostname: string | null; disc_year: number | null;
  discoverymethod: string | null; pl_rade: number | null; pl_bmasse: number | null;
  pl_orbper: number | null; pl_eqt: number | null; sy_dist: number | null;
  st_teff: number | null;
}

/* ── Helpers ─────────────────────────────────────────────────────────────── */

function transform(row: NasaRow, i: number): Planet {
  const dist = toNumberOrNull(row.sy_dist);
  const core = {
    name: row.pl_name ?? `Unknown-${i}`,
    hostStar: row.hostname ?? null,
    stellarTeff: toNumberOrNull(row.st_teff),
    radiusEarth: toNumberOrNull(row.pl_rade),
    massEarth: toNumberOrNull(row.pl_bmasse),
    orbitalPeriodDays: toNumberOrNull(row.pl_orbper),
    equilibriumTempK: toNumberOrNull(row.pl_eqt),
    discoveryYear: toNumberOrNull(row.disc_year),
    discoveryMethod: row.discoverymethod ?? null,
    distanceParsecs: dist,
    distanceLightYears: dist !== null ? dist * 3.26156 : null,
  };
  return {
    id: slugifyPlanetName(core.name, i),
    ...core,
    habitabilityScore: calculateHabitabilityScore(core),
    dataConfidence: calculateDataConfidence(core),
  };
}

function httpsGet(url: string, ms = 40_000): Promise<string> {
  return new Promise((resolve, reject) => {
    const req = https.get(url, {
      headers: { Accept: "application/json", "User-Agent": "ExoplanetExplorer/1.0" },
      // rejectUnauthorized false works around Windows corporate CA chain issues.
      // On Vercel (Linux), this has no effect since their CA bundle is complete.
      rejectUnauthorized: false,
    }, (res) => {
      if (res.statusCode !== 200) {
        reject(new Error(`NASA TAP HTTP ${res.statusCode}`));
        res.resume(); return;
      }
      const chunks: Buffer[] = [];
      res.on("data", (c: Buffer) => chunks.push(c));
      res.on("end", () => resolve(Buffer.concat(chunks).toString("utf-8")));
      res.on("error", reject);
    });
    req.setTimeout(ms, () => { req.destroy(new Error("NASA request timed out")); });
    req.on("error", reject);
  });
}

async function fetchAllFromNASA(): Promise<Planet[]> {
  if (process.env.NODE_ENV === "development") {
    console.log("[/api/exoplanets] Fetching all planets from NASA TAP…");
  }

  // Try static file first (generated by predev/prebuild script)
  try {
    const { existsSync, readFileSync } = await import("fs");
    const { join } = await import("path");
    const file = join(process.cwd(), "public", "data", "planets.json");
    if (existsSync(file)) {
      const raw: Planet[] = JSON.parse(readFileSync(file, "utf-8"));
      if (Array.isArray(raw) && raw.length > 100) {
        if (process.env.NODE_ENV === "development") {
          console.log(`[/api/exoplanets] ✓ Loaded ${raw.length} planets from planets.json`);
        }
        // Sort best-scoring first, then fix any duplicate IDs from NASA name variants
        const sorted = [...raw].sort((a, b) => b.habitabilityScore - a.habitabilityScore);
        return deduplicateIds(sorted);
      }
    }
  } catch {}

  // Fetch directly from NASA
  const params = new URLSearchParams({ query: SQL, format: "json", MAXREC: "5500" });
  const body = await httpsGet(`${NASA_TAP}?${params}`);
  const raw: NasaRow[] = JSON.parse(body);
  if (!Array.isArray(raw)) throw new Error("Non-array response from NASA");
  const planets = raw.map((r, i) => transform(r, i));
  if (process.env.NODE_ENV === "development") {
    console.log(`[/api/exoplanets] ✓ Fetched ${planets.length} planets from NASA`);
  }
  return deduplicateIds(planets);
}

async function getServerPlanets(): Promise<Planet[]> {
  // Fresh cache hit
  if (serverCache && Date.now() - serverCache.at < CACHE_TTL) return serverCache.planets;

  // Deduplicate concurrent first requests
  if (!fetchPromise) {
    fetchPromise = fetchAllFromNASA().then((planets) => {
      // Sort best-scoring first, then deduplicate IDs (NASA sometimes lists
      // the same planet under two name variants that slug identically).
      const sorted = [...planets].sort((a, b) => b.habitabilityScore - a.habitabilityScore);
      const unique = deduplicateIds(sorted);
      serverCache = { planets: unique, at: Date.now() };
      fetchPromise = null;
      return planets;
    }).catch((err) => {
      fetchPromise = null;
      throw err;
    });
  }
  return fetchPromise;
}

/* ── Route handler ───────────────────────────────────────────────────────── */

export async function GET(req: NextRequest) {
  const params = req.nextUrl.searchParams;
  const offset = Math.max(0, parseInt(params.get("offset") ?? "0", 10));
  const limit  = Math.min(500, Math.max(1, parseInt(params.get("limit") ?? "100", 10)));

  try {
    const all = await getServerPlanets();
    const slice = all.slice(offset, offset + limit);

    const body: ChunkResponse = {
      planets: slice,
      total: all.length,
      offset,
      limit,
      hasMore: offset + limit < all.length,
      source: serverCache ? "nasa" : "file",
    };

    return NextResponse.json(body, {
      headers: { "Cache-Control": "no-store" }, // chunks are always fresh from server cache
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error("[/api/exoplanets] Error:", msg);
    return NextResponse.json({ error: msg }, { status: 502 });
  }
}
